# Generated by Django 5.2.7 on 2025-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(choices=[('vinay', 'Vinay'), ('yashwanth', 'Yashwanth'), ('shashana', 'Shashana'), ('lakshman', 'Lakshman')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('week', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('todo', 'To-Do'), ('progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20)),
            ],
            options={
                'ordering': ['developer', 'week', 'day'],
            },
        ),
    ]
