# Generated by Django 5.2.7 on 2025-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='week',
            field=models.IntegerField(),
        ),
    ]
