# Generated by Django 5.2.7 on 2025-11-27 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_task_options_alter_task_day_alter_task_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='developer',
            new_name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='week',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
