# Generated by Django 5.2.7 on 2025-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_developer_task_assignee_remove_task_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
