# Generated by Django 5.2.7 on 2025-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_task_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(choices=[('vinay', 'Vinay Kumar V'), ('yashwanth', 'Yashwanth H V'), ('shashanka', 'Shashanka S'), ('lakshmana', 'Lakshmana M R')], max_length=20),
        ),
    ]
